#ifndef BOARD_CONFIG_H_
#define BOARD_CONFIG_H_

#define HW_VER_MAJOR 1
#define HW_VER_MINOR 0

#define FW_VER_MAJOR 1
#define FW_VER_MINOR 0

#define SHUNT_RESISTANCE 2.0e-3f
#define CURRENT_AMP_GAIN 10.0f

#define ONBOARD_TEMP_COEFF 0.0f
#define DC_VOLTAGE_COEFF 0.0f


#define FAST_MATH_TABLE_SIZE 0xFFF

#endif
