#ifndef BOARD_CONFIG_H_
#define BOARD_CONFIG_H_

#define HW_VER_MAJOR 1
#define HW_VER_MINOR 0

#define FW_VER_MAJOR 1
#define FW_VER_MINOR 0

#define ONBOARD_TEMP_COEFF 0.0f
#define DC_VOLTAGE_COEFF 756e-5f

#define DELTA_T 0.000044425f

#define OVERVOLTAGE_PROTECTION 24.1f
#define UNDERVOLTAGE_PROTECTION 7.9f

#define SUPPLY_PROTECTION 0.5f

#define FAST_MATH_TABLE_SIZE 0xFFF

#endif
