#ifndef BOARD_CONFIG_H_
#define BOARD_CONFIG_H_

#define HW_VER_MAJOR 1
#define HW_VER_MINOR 0

#define FW_VER_MAJOR 1
#define FW_VER_MINOR 0

#define MODEL_NUMBER 54025

#define ONBOARD_TEMP_COEFF 0.0f
#define DC_VOLTAGE_COEFF 756e-5f

#define DELTA_T 0.000044425f

#define OVERVOLTAGE_PROTECTION 26.1f
#define UNDERVOLTAGE_PROTECTION 7.9f

#define SUPPLY_PROTECTION 1.0f

#define FAST_MATH_TABLE_SIZE 0x1FFF

#define ACCEKERATION_FILTER_CUTOFF_FREQ 10.0f
#define VELOCITY_FILTER_CUTOFF_FREQ 5.0f
#define POSITION_FILTER_CUTOFF_FREQ 100.0f
#define CURRENT_FILTER_CUTOFF_FREQ 100.0f

#define UART_FIFO_BUFFER_SIZE  0xFFF

#endif
